- name: Get Jenkins Job Info
  community.general.jenkins_job_info:
    name: "{{item.job_name}}"
    user: admin
    password: admin123
    url: http://172.31.27.73:8080
  register: jenkins_job_status
  ignore_errors: true

- name: copy xml file
  ansible.builtin.template:
    src: mjob.xml
    dest: /tmp/test.xml
  when: jenkins_job_status.failed or override

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{item.job_name}}"
    password: admin123
    url: http://172.31.27.73:8080
    user: admin
  when: jenkins_job_status.failed or override
