- name: copy xml file
  ansible.builtin.template:
    src: sjob.xml
    dest: /tmp/test.xml

- name: Create a jenkins job
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/test.xml') }}"
    name: "{{iem.job_name}}"
    password: admin123
    url: http://172.31.27.73:8080
    user: admin
